# WebSite settings
title: Sami Alperen Akgün
email: sami.alperen.akgun@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Welcome to my personal blog! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samialperen.github.io"

# Social media 
github_username:  samialperen
linkedin_username: sami-alperen-akgun
google_scholar_id: 22An24AAAAAJ

# Build settings
markdown: kramdown
#theme: minima

# Add comments
disqus:
    shortname: https-samialperen-github-io
    
# Add google-analytics
google_analytics: UA-138872115-1   

# Improve google search result
plugins_dir:
  - jekyll-seo-tag
  - jekyll-sitemap


# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Master of Applied Science Student"
excerpt_separator: "<!--more-->"


#exclude: ['*.Rmd']

collections:
  projects:
    output: true
    permalink: /:collection/:name