title: Personal Blog of Sami Alperen Akgün
email: sami.alperen.akgun@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Welcome to my personal blog! In this blog, I will
    try to share my experience and thoughts about academic life, travel, literature
    technology, music, movies and TV-series. You can use/share any information
    in here as long as you provide reference. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samialperen.github.io"

# Social media 
github_username:  samialperen
linkedin_username: sami-alperen-akgun

markdown: kramdown
theme: minima

# Add comments
disqus:
    shortname: https-samialperen-github-io
    
# Add google-analytics
google_analytics: UA-138872115-1   

# Improve google search result
plugins_dir:
  - jekyll-seo-tag
